jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:rHf8VPz2bKGl3UMUeSzwPXa8nBA=,iv:JJFcwUunDfMoNUABiXRfV9C5BuaGLQYCvGDFyBWCxgU=,tag:q4u8wS1BtTEDRjiTVVFXOg==,type:str]
        client_secret: ENC[AES256_GCM,data:c4AKrOOkxFBkzghTOL5+36WjBVnV19E305ER66Rs136Ot4rVPjv9CQ==,iv:ET6a4aoWAnkNa3DbVKP8Ot1t0wZyIAZGIeo0yh2h4p4=,tag:aSyKtnupIET6udr6V7WSDw==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    config:
      QuotaManager:
        quota_overrides:
          lamc97: ENC[AES256_GCM,data:tDU=,iv:TWk0KE2H7k0o0TyH6wYkJJ4wxzcRadKMYbGi8uC5AAw=,tag:bw/vwjo3Dt6X1bxxq2L9lg==,type:int]
          cxro-2dcc: ENC[AES256_GCM,data:mdk=,iv:GVhLs0xxdld+4u6Fr2vTxZCp1sieCZY8uSzrvlj6I0o=,tag:BXcLArIVk/lLmNtNNyn2wA==,type:int]
          _shared: ENC[AES256_GCM,data:shg=,iv:BVuaqmbBgXLIDu+E5zismgjtvMd2G2smT/QGQm0Dlrs=,tag:RosdLLoex588oIc8LzkU+A==,type:int]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2024-05-02T15:00:10Z'
    enc: CiUA4OM7eK4gZY/ziup1ECZNetmXDilkTlejSe/paVHp4oQNcGKyEkkAXoW3Jn3Yvn4zrnsGQWy+wmqCuqH+k82OaT9c+HE4f9aaIaNuPBLfCyTW2bJ0uzMwEpMNQCX8vBG2trOguQqJBYrDKTpB5WWV
  lastmodified: '2025-10-13T15:44:30Z'
  mac: ENC[AES256_GCM,data:WCMiVS/Bzqn35VW5qestwAX6Kff7pzTgfwZ5ZjC/Ho2ntWl1/6ODfIwI0P5vXbVYpkAjnqsi/rlnWhUZRL0gM+bJvWZFgiolmfTygm/33nUww86tWAfwsvXrhO/B93ROc9//gOPV/ICcnqePT6ohSMvPBAnoisCQc8fyJ3F47CI=,iv:HA94gnBOZgsnL60lIZq6T1VY7mtV05PbSXlgVGbmu8o=,tag:B57sslWgE4vHlhRz9X03HQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
